version: "2"

services:
  rabbitmq:
    build: .
    container_name: "rabbitmq-microservice-advance"
    # env_file: .env
    # volumes:
    #   - ./logs:/usr/src/app/logs
    #   - ./src:/usr/src/app/src
    #   - ./ssl:/usr/src/app/ssl
    #   - ./package.json:/usr/src/app/package.json
    ports:
      - 15671:15671
      - 15672:15672
      - 5672:5672
