# Generated by Django 2.2.3 on 2019-10-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodel',
            name='time_created',
            field=models.BigIntegerField(blank=True, default=1571985497, editable=False),
        ),
        migrations.AlterField(
            model_name='permissionmodel',
            name='time_modified',
            field=models.BigIntegerField(blank=True, default=1571985497, editable=False),
        ),
    ]
