# Generated by Django 2.0.5 on 2019-10-24 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('time_created', models.BigIntegerField(default=1571926144, editable=False)),
                ('time_modified', models.BigIntegerField(default=1571926144, editable=False)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
