# Generated by Django 2.0.5 on 2019-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20191026_0853'),
        ('account', '0002_auto_20191026_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='role_account', to='role.RoleModel'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='time_created',
            field=models.BigIntegerField(default=1572080027, editable=False),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='time_modified',
            field=models.BigIntegerField(default=1572080027, editable=False),
        ),
    ]
