# Generated by Django 2.2.3 on 2019-10-25 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20191025_0638'),
        ('permission', '0002_auto_20191025_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_created', models.BigIntegerField(blank=True, default=1571985497, editable=False)),
                ('time_modified', models.BigIntegerField(blank=True, default=1571985497, editable=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_role', to='account.AccountModel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_role', to='account.AccountModel')),
                ('permissions', models.ManyToManyField(blank=True, related_name='permission_role', to='permission.PermissionModel')),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
