# Generated by Django 2.2.3 on 2019-10-25 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('time_created', models.BigIntegerField(default=1571989201, editable=False)),
                ('time_modified', models.BigIntegerField(default=1571989201, editable=False)),
            ],
            options={
                'db_table': 'account_info',
            },
        ),
    ]
