# Generated by Django 2.2.3 on 2019-10-25 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountinfo', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.TextField(validators=[django.core.validators.RegexValidator('^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\\$%\\^&\\*])(?=.{8,})', '(?=.*[a-z])\tThe string must contain at least 1 lowercase alphabetical character. (?=.*[A-Z])\tThe string must contain at least 1 uppercase alphabetical character. (?=.*[0-9])\tThe string must contain at least 1 numeric character. (?=.[!@#\\$%\\^&])\tThe string must contain at least one special character, but we are escaping reserved RegEx characters to avoid conflict. (?=.{8,})\tThe string must be eight characters or longer')])),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('time_created', models.BigIntegerField(default=1571989201, editable=False)),
                ('time_modified', models.BigIntegerField(default=1571989201, editable=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_account', to='accountinfo.AccountInfoModel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_account', to='accountinfo.AccountInfoModel')),
                ('roles', models.ManyToManyField(blank=True, related_name='role_account', to='role.RoleModel')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
