# Generated by Django 2.0.5 on 2019-10-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191023_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='time_modified',
            field=models.BigIntegerField(default=1571843093, editable=False),
        ),
    ]
