# Generated by Django 2.0.5 on 2019-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191023_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='time_created',
            field=models.BigIntegerField(default=1571844826, editable=False),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='time_modified',
            field=models.BigIntegerField(default=1571844826, editable=False),
        ),
    ]
