# Generated by Django 2.2.3 on 2019-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191023_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='time_created',
            field=models.BigIntegerField(default=1571984972, editable=False),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='time_modified',
            field=models.BigIntegerField(default=1571984972, editable=False),
        ),
    ]
