# Generated by Django 2.2.3 on 2019-10-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191025_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='time_created',
            field=models.BigIntegerField(default=1571985497, editable=False),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='time_modified',
            field=models.BigIntegerField(default=1571985497, editable=False),
        ),
    ]
