"""
Django settings for newsservice project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3^q94f_gq7h)ed5-eg%nkd#m5r@&6-vfo=xh-99j^qqx%8!v@i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # install graphql
    'graphene_django',

    # app
    'src.apps.account',
    'src.apps.role',
    'src.apps.permission',
    'src.apps.category',
    'src.apps.post'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newsservice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newsservice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
def get_db_host():
    try:
        mysql_host = os.environ['MYSQL_HOST']
        return mysql_host
    except Exception:
        # dev
        return '42.112.31.240'
        # localhost
        # return '127.0.0.1'


def get_db_port():
    try:
        mysql_port = os.environ['MYSQL_PORT']
        return mysql_port
    except Exception:
        return '8806'


def get_db_password():
    try:
        mysql_password = os.environ['MYSQL_ROOT_PASSWORD']
        return mysql_password
    except Exception:
        # dev
        return 'm1tkh!u123'
        # localhost
        # return 'pwd'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'news_service_ex',
        'USER': 'root',
        'PASSWORD': get_db_password(),
        'HOST': get_db_host(),
        'PORT': get_db_port(),
        'OPTIONS': {'charset': 'utf8mb4'}
    }
}


# import graphql
GRAPHENE = {
    'SCHEMA': 'src.graphql.schema.schema',
    # 'MIDDLEWARE': [
    #     'src.middlewares.auth.check_permission',
    # ]
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
